### ISSUE TITLE
Missing Classes

### ISSUE THREAD

**Issue by pavankumarpisipati** [mikera/swing-console#2]
There are missing class files in swing-console project. Like mikera.gui.Frames, mikera.image.Colours and mikera.util.Rand, etc. Can you upload the complete project please.

**Comment by mikera** [comment]
Hi there, these classes are in the `mikera-gui` dependency. If you are using Maven or some other dependency manager then these should be downloaded automatically.... if not you can get the jar files manually from here:

https://clojars.org/repo/net/mikera/mikera-gui/0.3.1/
