### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by KernelDev** [mikera/swing-console#3]
Hello mikera,

I would like to use your project in one of my applications. Could you provide any licensing for your code or am I fine to use it. My usage is not commercial. We wont sell your product. I just wanted to build a Kernelbuildtool for our development area. Am I allowed to do so?

Kind regards,

KernelDev

PS: Message Service was removed and you provided no email in your profile. So that was the only reliable way

**Comment by mikera** [comment]
Sure... I am happy to license under LGPL, should be fine for you to use as a library.
